//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookShopPlusEntities : DbContext
    {
        public BookShopPlusEntities()
            : base("name=BookShopPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookRatings> BookRatings { get; set; }
        public DbSet<Books> Books { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Collections> Collections { get; set; }
        public DbSet<Config> Config { get; set; }
        public DbSet<IntegralGoods> IntegralGoods { get; set; }
        public DbSet<IntegralSection> IntegralSection { get; set; }
        public DbSet<OrderBook> OrderBook { get; set; }
        public DbSet<OrderIntegral> OrderIntegral { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Publishers> Publishers { get; set; }
        public DbSet<ReaderComments> ReaderComments { get; set; }
        public DbSet<RecomBooks> RecomBooks { get; set; }
        public DbSet<Registration> Registration { get; set; }
        public DbSet<ScoreHistory> ScoreHistory { get; set; }
        public DbSet<SearchKeywords> SearchKeywords { get; set; }
        public DbSet<Seckill> Seckill { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<sysman> sysman { get; set; }
        public DbSet<TemporaryCart> TemporaryCart { get; set; }
        public DbSet<test1> test1 { get; set; }
        public DbSet<UserRoles> UserRoles { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserStates> UserStates { get; set; }
        public DbSet<visitBook> visitBook { get; set; }
    }
}
