//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Collections = new HashSet<Collections>();
            this.Seckill = new HashSet<Seckill>();
            this.IntegralGoods = new HashSet<IntegralGoods>();
            this.OrderBook = new HashSet<OrderBook>();
            this.ReaderComments = new HashSet<ReaderComments>();
            this.visitBook = new HashSet<visitBook>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int PublisherId { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string ISBN { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public decimal UnitPrice { get; set; }
        public string ContentDescription { get; set; }
        public string TOC { get; set; }
        public int CategoryId { get; set; }
        public int Clicks { get; set; }
        public int Flag { get; set; }
        public Nullable<decimal> ClearPrice { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Collections> Collections { get; set; }
        public virtual ICollection<Seckill> Seckill { get; set; }
        public virtual Publishers Publishers { get; set; }
        public virtual ICollection<IntegralGoods> IntegralGoods { get; set; }
        public virtual ICollection<OrderBook> OrderBook { get; set; }
        public virtual ICollection<ReaderComments> ReaderComments { get; set; }
        public virtual ICollection<visitBook> visitBook { get; set; }
    }
}
