//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderBook = new HashSet<OrderBook>();
            this.OrderIntegral = new HashSet<OrderIntegral>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int UserId { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> flag { get; set; }
        public string personName { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<decimal> sendCash { get; set; }
        public string userCancelReason { get; set; }
        public string OrderRemark { get; set; }
    
        public virtual ICollection<OrderBook> OrderBook { get; set; }
        public virtual ICollection<OrderIntegral> OrderIntegral { get; set; }
        public virtual Users Users { get; set; }
    }
}
