//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderIntegral
    {
        public int Id { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> IntegralGoodsID { get; set; }
        public int Quantity { get; set; }
        public decimal PaymentIntegral { get; set; }
    
        public virtual IntegralGoods IntegralGoods { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
