//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreHistory
    {
        public int Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UserId { get; set; }
        public int Flag { get; set; }
        public int SingleScore { get; set; }
        public string Descriptions { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
