//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Collections = new HashSet<Collections>();
            this.Orders = new HashSet<Orders>();
            this.ReaderComments = new HashSet<ReaderComments>();
            this.ReaderComments1 = new HashSet<ReaderComments>();
            this.Registration = new HashSet<Registration>();
            this.ScoreHistory = new HashSet<ScoreHistory>();
        }
    
        public int Id { get; set; }
        public string LoginId { get; set; }
        public string LoginPwd { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int UserRoleId { get; set; }
        public string RegisterIp { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<int> scoreTotal { get; set; }
        public Nullable<int> scoreCurrent { get; set; }
        public string HeadImg { get; set; }
        public int IsFrozen { get; set; }
    
        public virtual ICollection<Collections> Collections { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ReaderComments> ReaderComments { get; set; }
        public virtual ICollection<ReaderComments> ReaderComments1 { get; set; }
        public virtual ICollection<Registration> Registration { get; set; }
        public virtual ICollection<ScoreHistory> ScoreHistory { get; set; }
    }
}
